artifact: Chainsaw_LoginAttacks
tool: Chainsaw
description: Login Attacks
discovery:
  filename_patterns:
    - login_attacks.csv
  foldername_patterns:
    - chainsaw
  required_headers:
    - timestamp
    - Event ID
    - Computer
    - Channel
    - detections
    - path
  strict_filename_match: true
  strict_folder_match: false
  strict_header_match: false
enabled: true
