artifact: EventLogs
tool: EZ Tools
description: Event Logs
discovery:
  filename_patterns:
    - _EvtxECmd_Output.csv
  foldername_patterns:
    - EventLogs
  required_headers:
    - TimeCreated
    - EventId
    - Channel
    - Computer
    - MapDescription
    - SourceFile
    - PayloadData1
  strict_filename_match: false
  strict_folder_match: false
  strict_header_match: false
enabled: true
filters:
  extensions: []
  paths: []
  event_channel_filters:
    Security: [1102, 4624, 4625, 4648, 4698, 4702, 4720, 4722, 4723, 4724, 4725, 4726, 4732, 4756]
    System: [7045]
    Application: [1000, 1001]
    Microsoft-Windows-PowerShell/Operational: [4100, 4103, 4104]
    Microsoft-Windows-RemoteDesktopServices-RdpCoreTS/Operational: [72, 98, 104, 131, 140]
    Microsoft-Windows-TerminalServices-LocalSessionManager/Operational: [21, 22]
    Microsoft-Windows-TerminalServices-RemoteConnectionManager/Operational: [261, 1149]
    Microsoft-Windows-TaskScheduler/Operational: [106, 140, 141, 129, 200, 201]
    Microsoft-Windows-WinRM/Operational: [169]
    SentinelOne/Operational: [1, 31, 55, 57, 67, 68, 77, 81, 93, 97, 100, 101, 104, 110]
  
  provider_filters:
    edgeupdate: [0]
    SentinelHelperService: [0]
    brave: [0]
    Edge: [256]
    SentinelOne: [1, 31, 55, 57, 67, 68, 77, 81] 
