artifact: EventLogs
tool: EZ Tools
description: Event Logs
ignore_filters: false
discovery:
  filename_patterns:
    - _EvtxECmd_Output.csv
  foldername_patterns:
    - EventLogs
  required_headers:
    - TimeCreated
    - EventId
    - Channel
    - Computer
    - MapDescription
    - SourceFile
    - PayloadData1
  strict_filename_match: false
  strict_folder_match: false
  strict_header_match: false
enabled: true
filters:
  extensions: []
  paths: []
  event_channel_filters:
    Security: [1102, 4624, 4625, 4648, 4698, 4702, 4720, 4722, 4723, 4724, 4725, 4726, 4732, 4756]
    System: [7045]
    Application: [1000, 1001]
    Microsoft-Windows-PowerShell/Operational: [4100, 4103, 4104]
    Microsoft-Windows-RemoteDesktopServices-RdpCoreTS/Operational: [72, 98, 104, 131, 140]
    Microsoft-Windows-TerminalServices-LocalSessionManager/Operational: [21, 22]
    Microsoft-Windows-TerminalServices-RemoteConnectionManager/Operational: [261, 1149]
    Microsoft-Windows-TaskScheduler/Operational: [106, 140, 141, 129, 200, 201]
    Microsoft-Windows-WinRM/Operational: [169]
    SentinelOne/Operational: [1, 31, 55, 57, 67, 68, 77, 81, 93, 97, 100, 101, 104, 110]
  
  provider_filters:
    edgeupdate: [0]
    SentinelHelperService: [0]
    brave: [0]
    Edge: [256]
    SentinelOne: [1, 31, 55, 57, 67, 68, 77, 81] 

# --------------------------------------------------------------------------------
# YAML Configuration Notes for Event Logs Artifact
#
# ignore_filters:
#   - When true, disables both channel and provider filtering.
#   - All event log rows will be included regardless of Event ID or Provider.
#
# filters:
#   event_channel_filters:
#     - Maps log channels (e.g., Security, System) to allowed Event IDs.
#     - Only events matching both channel and listed Event IDs are included.
#     - Set ignore_filters: true to bypass this.
#
#   provider_filters:
#     - Filters events by their Provider name (e.g., "SentinelOne") and Event IDs.
#     - Useful for filtering logs that use custom providers instead of standard channels.
#
#   extensions & paths:
#     - These are ignored by the event log parser but must be defined to match schema.
#     - Leave them as empty lists: extensions: [], paths: []
#
# required_headers:
#   - All listed columns must be present in the CSV for it to be parsed.
#   - If any required header is missing, the file will be skipped.
#
# discovery:
#   - Controls how the parser finds input files.
#   - filename_patterns: looks for files like "_EvtxECmd_Output.csv"
#   - foldername_patterns: looks for folders like "EventLogs"
#   - strict_* flags: allow partial or fuzzy matching when set to false.
# --------------------------------------------------------------------------------
