artifact: Axiom_MRUFolderAccess
tool: Axiom
description: MRU Folder Access
discovery:
  filename_patterns:
    - MRU Folder Access.csv
  foldername_patterns:
    - axiom
  required_headers:
    - Registry Key Modified Date/Time - UTC+00:00 (M/d/yyyy)
    - Folder Accessed
    - Application Name
  strict_filename_match: true
  strict_folder_match: false
  strict_header_match: false
enabled: true