artifact: Axiom_EventLogs
tool: Axiom
description: Windows Event Logs
discovery:
  filename_patterns:
    - Windows Event Logs.csv
  foldername_patterns:
    - axiom
  required_headers:
    - Record
    - Tags
    - Comments
    - Event ID
    - Event Type
    - Created Date/Time - UTC+00:00 (M/d/yyyy)
    - Event Record ID
    - Event Description Summary
    - Computer
    - Event Data
    - Source
  strict_filename_match: true
  strict_folder_match: false
  strict_header_match: false
enabled: true
filters:
  provider_filters:
    Microsoft-Windows-Security-Auditing: [1102, 4624, 4625, 4648, 4698, 4702, 4720, 4722, 4723, 4724, 4725, 4726, 4732, 4756]
    Service Control Manager: [7045]
    Microsoft-Windows-TerminalServices-LocalSessionManager: [21, 22]
    Windows Error Reporting: [1000, 1001]
    Microsoft-Windows-WinRM: [169]
    SentinelOne: [1, 31, 55, 57, 67, 68, 77, 81, 93, 97, 100, 101, 104, 110]
    Microsoft-Windows-PowerShell: [4104]

