artifact: Axiom_UserAssist
tool: Axiom
description: UserAssist
discovery:
  filename_patterns:
    - UserAssist.csv
  foldername_patterns:
    - axiom
  required_headers:
    - Last Execution Date/Time - UTC+00:00 (M/d/yyyy)
    - Program Path
    - Program Name
    - Execution Count
  strict_filename_match: true
  strict_folder_match: false
  strict_header_match: false
enabled: true